//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVertice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alojamiento_has_tipo_alojamiento
    {
        public int Id { get; set; }
        public int AlojamientoId { get; set; }
        public int AlojamientoId1 { get; set; }
    
        public virtual Tipo_Alojamiento Tipo_Alojamiento { get; set; }
        public virtual Alojamiento Alojamiento { get; set; }
    }
}
