//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVertice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseReservaVerticeEntities : DbContext
    {
        public DatabaseReservaVerticeEntities()
            : base("name=DatabaseReservaVerticeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alojamiento> AlojamientoSet { get; set; }
        public virtual DbSet<Reserva> ReservaSet { get; set; }
        public virtual DbSet<Pais> PaisSet { get; set; }
        public virtual DbSet<Programa> ProgramaSet { get; set; }
    }
}
