//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVertice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseReservaVerticeEntities : DbContext
    {
        public DatabaseReservaVerticeEntities()
            : base("name=DatabaseReservaVerticeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tipo_Alojamiento> Tipo_AlojamientoSet { get; set; }
        public virtual DbSet<Alojamiento> AlojamientoSet { get; set; }
        public virtual DbSet<alojamiento_has_tipo_alojamiento> alojamiento_has_tipo_alojamientoSet { get; set; }
        public virtual DbSet<Programa_has_alojamiento> Programa_has_alojamientoSet { get; set; }
        public virtual DbSet<Programa> ProgramaSet { get; set; }
        public virtual DbSet<Reserva_programa> Reserva_programaSet { get; set; }
        public virtual DbSet<Servicio_adicional> Servicio_adicionalSet { get; set; }
        public virtual DbSet<alojamiento_has_servicio_adicional> alojamiento_has_servicio_adicionalSet { get; set; }
        public virtual DbSet<Reserva_alojamiento> Reserva_alojamientoSet { get; set; }
        public virtual DbSet<Reserva> ReservaSet { get; set; }
        public virtual DbSet<Reserva_detalle_programa> Reserva_detalle_programaSet { get; set; }
        public virtual DbSet<Reserva_excursion> Reserva_excursionSet { get; set; }
        public virtual DbSet<Excursion> ExcursionSet { get; set; }
    }
}
